policy:
  approval:
    - and:
      - anyone approves
      - or:
        - admin approves
        - and:
          - day01 owners approve
          - day02 owners approve
approval_rules:
  - name: anyone approves
    options:
      ignore_update_merges: true
    requires:
      count: 1
      organizations: ["VideoAmp"]
      users: ["srabraham"]
  - name: admin approves
    options:
      allow_author: true
      allow_contributor: true
      allow_non_author_contributor: true
      ignore_update_merges: true
    requires:
      count: 1
      users:
        - "srabraham"
  - name: day01 owners approve
    if:
      changed_files:
        paths: ["day01/.*"]
    options:
      ignore_update_merges: true
    requires:
      count: 1
      organizations: ["VideoAmp"]
      users: ["srabraham"]
  - name: day02 owners approve
    if:
      changed_files:
        paths: ["day02/.*"]
    options:
      ignore_update_merges: true
    requires:
      count: 1
      organizations: ["VideoAmp"]
      users: ["srabraham"]
