policy:
  approval:
    - and:
      - lgtm
      - or:
        - admin approval
        - and:
          - day01 owners approval
          - day02 owners approval
approval_rules:
  - name: lgtm
    options:
      ignore_update_merges: true
    requires:
      count: 1
      organizations: ["VideoAmp"]
      users: ["srabraham"]
  - name: admin approval
    options:
      allow_author: true
      allow_contributor: true
      allow_non_author_contributor: true
      ignore_update_merges: true
    requires:
      count: 1
      users:
        - "srabraham"
  - name: day01 owners approval
    if:
      changed_files:
        paths: ["day01/.*"]
    options:
      allow_author: true
      allow_contributor: true
      allow_non_author_contributor: true
      ignore_update_merges: true
    requires:
      count: 1
      organizations: ["VideoAmp"]
      users: ["srabraham"]
  - name: day02 owners approval
    if:
      changed_files:
        paths: ["day02/.*"]
    options:
      allow_author: true
      allow_contributor: true
      allow_non_author_contributor: true
      ignore_update_merges: true
    requires:
      count: 1
      organizations: ["VideoAmp"]
      users: ["srabraham"]
