policy:
  approval:
    - and:
      - LGTM
      - or:
        - admin approval
        - and:
          - day01 owners approval
          - day02 owners approval
approval_rules:
  - name: LGTM
    description: Get an approval from another person
    options:
      ignore_update_merges: true
    requires:
      count: 1
      organizations: ["VideoAmp"]
      users: ["srabraham"]
  - name: admin approval
    description: Admins can apply codeowners approval for any PR
    options:
      allow_author: true
      allow_contributor: true
      allow_non_author_contributor: true
      ignore_update_merges: true
    requires:
      count: 1
      users:
        - "srabraham"
  - name: day01 owners approval
    description: codeowners approval - an author can self-approve
    if:
      changed_files:
        paths: ["day01/.*"]
    options:
      allow_author: true
      allow_contributor: true
      allow_non_author_contributor: true
      ignore_update_merges: true
    requires:
      count: 1
      organizations: ["VideoAmp"]
      users: ["srabraham"]
  - name: day02 owners approval
    description: codeowners approval - an author can self-approve
    if:
      changed_files:
        paths: ["day02/.*"]
    options:
      allow_author: true
      allow_contributor: true
      allow_non_author_contributor: true
      ignore_update_merges: true
    requires:
      count: 1
      organizations: ["VideoAmp"]
      users: ["srabraham"]
